/**
 * Palavras de busca para cada emoji.
 *
 * Existe porque a busca do seletor filtrava so o nome do grupo — "Rostos",
 * "Gestos", "Coracoes". Digitar "feliz", "risada" ou "coracao" nao achava
 * nada, porque os emojis sao apenas caracteres e nao carregam nome nenhum.
 *
 * Os termos sao em portugues e escritos como as pessoas digitam, incluindo
 * girias e a forma sem acento: quem esta com pressa nao poe acento, e a busca
 * tambem normaliza os dois lados. Mais de um termo por emoji de proposito —
 * o mesmo desenho e "chorando de rir" para uns e "risada" para outros.
 */
export const PALAVRAS_DE_EMOJI: Record<string, string> = {
  // --- Rostos ---------------------------------------------------------------
  '😀': 'sorriso feliz alegre contente',
  '😃': 'sorriso feliz alegre animado',
  '😄': 'sorriso feliz rindo alegre',
  '😁': 'sorriso dentes feliz radiante',
  '😆': 'rindo risada gargalhada',
  '😅': 'rindo suor alivio nervoso ufa',
  '🤣': 'rolando de rir gargalhada risada chorando',
  '😂': 'chorando de rir lagrima risada kkk',
  '🙂': 'sorriso leve ok tranquilo',
  '🙃': 'invertido ironia sarcasmo de cabeca para baixo',
  '😉': 'piscada flerte piscadinha',
  '😊': 'feliz timido sorriso corado fofo',
  '😇': 'anjo inocente santo auréola',
  '🥰': 'amor apaixonado coracoes carinho',
  '😍': 'apaixonado amor olhos de coracao',
  '🤩': 'estrela uau incrivel deslumbrado',
  '😘': 'beijo mandando beijo',
  '😗': 'beijo assobio',
  '😚': 'beijo carinho olhos fechados',
  '😙': 'beijo sorriso',
  '😋': 'delicia gostoso lingua saboroso fome',
  '😛': 'lingua brincadeira',
  '😜': 'lingua piscada brincadeira zoando',
  '🤪': 'louco maluco doido biruta',
  '😝': 'lingua careta nojo',
  '🤑': 'dinheiro rico ganancia cifrao grana',
  '🤗': 'abraco acolhendo',
  '🤭': 'ops vergonha risinho mao na boca',
  '🤫': 'silencio shh segredo quieto',
  '🤔': 'pensando duvida hmm refletindo',
  '🤐': 'boca fechada ziper segredo calado',
  '🤨': 'desconfiado sobrancelha duvida serio',
  '😐': 'neutro indiferente sem reacao',
  '😑': 'sem expressao entediado tedio',
  '😶': 'sem boca calado mudo',
  '😏': 'malicioso safado sorrisinho ironico',
  '😒': 'chateado desgosto contrariado',
  '🙄': 'revirando os olhos tedio ironia',
  '😬': 'careta constrangido tenso eita',
  '🤥': 'mentira pinoquio nariz mentiroso',
  '😌': 'aliviado calmo sereno',
  '😔': 'triste desanimado cabisbaixo',
  '😪': 'sono cansado sonolento',
  '🤤': 'baba desejo fome agua na boca',
  '😴': 'dormindo sono zzz',
  '😷': 'mascara doente gripe',
  '🤒': 'febre termometro doente',
  '🤕': 'machucado ferido curativo',
  '🤢': 'enjoado nojo enjoo',
  '🤮': 'vomitando vomito passando mal',
  '🤧': 'espirro gripe resfriado',
  '🥵': 'calor quente suando derretendo',
  '🥶': 'frio congelando gelado',
  '🥴': 'tonto bebado zonzo',
  '😵': 'tonto morto xis nocaute',
  '🤯': 'explodindo a mente chocado mente explodindo',
  '🤠': 'caubói chapeu cowboy',
  '🥳': 'festa comemorar aniversario parabens',
  '😎': 'oculos legal estiloso de boa',
  '🤓': 'nerd oculos estudioso',
  '🧐': 'monoculo analisando investigando',
  '😕': 'confuso incerto',
  '😟': 'preocupado aflito',
  '🙁': 'triste leve insatisfeito',
  '😮': 'surpreso boca aberta uau',
  '😯': 'surpreso pasmo',
  '😲': 'chocado espantado assombrado',
  '😳': 'corado envergonhado surpreso vermelho',
  '🥺': 'pidao suplicante carinha de pidao por favor',
  '😦': 'assustado franzindo',
  '😧': 'angustiado aflito',
  '😨': 'medo assustado apavorado',
  '😰': 'ansioso suor medo nervoso',
  '😥': 'triste decepcionado aliviado',
  '😢': 'chorando lagrima triste',
  '😭': 'chorando muito soluco choro',
  '😱': 'grito medo panico pavor',
  '😖': 'frustrado incomodado',
  '😣': 'esforco perseverando sofrendo',
  '😞': 'decepcionado desapontado',
  '😓': 'suor frio triste',
  '😩': 'cansado exausto sofrendo',
  '😫': 'cansado frustrado esgotado',
  '🥱': 'bocejo sono entediado',
  '😤': 'bufando raiva vapor indignado',
  '😡': 'raiva bravo vermelho furioso',
  '😠': 'bravo raiva irritado',
  '🤬': 'palavrao xingando raiva',
  '😈': 'diabo travesso safado',
  '👿': 'diabo raiva demonio',
  '💀': 'caveira morto morri',
  '☠️': 'caveira perigo morte',
  '💩': 'coco merda bosta',
  '🤡': 'palhaco palhacada',
  '👹': 'ogro monstro',
  '👺': 'goblin duende',
  '👻': 'fantasma assombracao',
  '👽': 'alien et extraterrestre',
  '🤖': 'robo bot',
  '😺': 'gato sorriso',
  '😸': 'gato feliz',
  '😹': 'gato rindo chorando',
  '😻': 'gato apaixonado',
  '😼': 'gato malicioso',
  '😽': 'gato beijo',
  '🙀': 'gato assustado',
  '😿': 'gato chorando',
  '😾': 'gato bravo',

  // --- Gestos ---------------------------------------------------------------
  '👍': 'joia positivo curtir legal ok polegar',
  '👎': 'negativo nao gostei polegar para baixo',
  '👌': 'ok certo perfeito',
  '🤌': 'italiano dedos gesto',
  '🤏': 'pouco pequeno pitada',
  '✌️': 'paz vitoria dois',
  '🤞': 'dedos cruzados sorte torcendo',
  '🤟': 'te amo amor sinal',
  '🤘': 'rock chifrinho metal',
  '🤙': 'me liga shaka relaxa',
  '👈': 'aponta esquerda',
  '👉': 'aponta direita',
  '👆': 'aponta cima',
  '👇': 'aponta baixo',
  '☝️': 'atencao um dedo cima',
  '✋': 'mao parada alto',
  '🤚': 'mao levantada',
  '🖐️': 'mao aberta cinco dedos',
  '🖖': 'vulcano spock saudacao',
  '👋': 'tchau ola aceno oi',
  '🤝': 'aperto de mao acordo negocio',
  '🙏': 'obrigado por favor reza oracao',
  '✍️': 'escrevendo anotando',
  '💅': 'unha esmalte to nem ai',
  '🤳': 'selfie foto',
  '💪': 'forca musculo biceps academia',
  '🦾': 'braco mecanico protese',
  '🦿': 'perna mecanica protese',
  '🦵': 'perna',
  '🦶': 'pe',
  '👂': 'orelha ouvido escutar',
  '🦻': 'aparelho auditivo',
  '👃': 'nariz cheiro',
  '🧠': 'cerebro mente inteligencia',
  '🫀': 'coracao orgao anatomico',
  '🫁': 'pulmao respirar',
  '🦷': 'dente',
  '🦴': 'osso',
  '👀': 'olhos olhando vendo',
  '👁️': 'olho',
  '👅': 'lingua',
  '👄': 'boca labios',
  '💋': 'beijo marca de batom',
  '🩸': 'sangue gota',

  // --- Coracoes -------------------------------------------------------------
  '❤️': 'coracao amor vermelho',
  '🧡': 'coracao laranja',
  '💛': 'coracao amarelo',
  '💚': 'coracao verde',
  '💙': 'coracao azul',
  '💜': 'coracao roxo',
  '🖤': 'coracao preto',
  '🤍': 'coracao branco',
  '🤎': 'coracao marrom',
  '💔': 'coracao partido decepcao termino',
  '❣️': 'coracao exclamacao',
  '💕': 'coracoes dois amor',
  '💞': 'coracoes girando amor',
  '💓': 'coracao batendo pulsando',
  '💗': 'coracao crescendo',
  '💖': 'coracao brilhante',
  '💘': 'coracao flecha cupido',
  '💝': 'coracao presente laco',
  '💟': 'coracao decoracao',
  '♥️': 'coracao naipe copas',
  '💌': 'carta de amor',
  '💤': 'dormindo sono zzz',
  '💢': 'raiva irritacao veia',
  '💥': 'explosao boom',
  '💫': 'tontura estrelas girando',
  '💦': 'gotas suor agua',
  '💨': 'vento correndo fumaca',
  '🕳️': 'buraco',
  '💣': 'bomba explosivo',
  '💬': 'balao de fala mensagem conversa',
  '👁️‍🗨️': 'olho balao testemunha',
  '🗨️': 'balao fala esquerda',
  '🗯️': 'balao raiva grito',
  '💭': 'balao pensamento pensando',

  // --- Festa ----------------------------------------------------------------
  '🎉': 'festa comemoracao parabens confete',
  '🎊': 'confete festa comemoracao',
  '🎈': 'balao festa aniversario',
  '🎁': 'presente',
  '🎀': 'laco fita',
  '🪅': 'pinhata festa',
  '🎂': 'bolo aniversario',
  '🍰': 'bolo fatia doce',
  '🧁': 'cupcake doce bolinho',
  '🍾': 'champanhe espumante comemorar',
  '🥂': 'brinde tacas comemorar',
  '🍻': 'brinde cerveja canecas',
  '🍺': 'cerveja chopp breja',
  '🍷': 'vinho taca',
  '🥃': 'whisky dose',
  '🍸': 'drink coquetel martini',
  '🍹': 'drink tropical coquetel',
  '🧃': 'suco caixinha',
  '☕': 'cafe cafezinho',
  '🍵': 'cha',
  '🥤': 'refrigerante copo canudo',
  '🧋': 'bubble tea cha',
  '🍕': 'pizza',
  '🍔': 'hamburguer lanche',
  '🍟': 'batata frita',
  '🌭': 'cachorro quente hot dog',
  '🥪': 'sanduiche',
  '🌮': 'taco mexicano',
  '🌯': 'burrito wrap',
  '🍿': 'pipoca cinema filme',
  '🧂': 'sal',
  '🥓': 'bacon',
  '🍳': 'ovo frito',
  '🥞': 'panqueca',
  '🧇': 'waffle',
  '🍞': 'pao',

  // --- Jogos ----------------------------------------------------------------
  '🎮': 'videogame jogo controle gamer',
  '🕹️': 'joystick fliperama arcade',
  '🎲': 'dado sorte',
  '🎯': 'alvo dardo mira acertou',
  '🎰': 'cassino caca niquel',
  '🃏': 'coringa carta',
  '🀄': 'mahjong',
  '🎱': 'sinuca bilhar bola oito',
  '🏓': 'pingue pongue tenis de mesa',
  '🏸': 'badminton peteca',
  '🥅': 'gol trave rede',
  '⚽': 'futebol bola',
  '🏀': 'basquete bola',
  '🏈': 'futebol americano',
  '⚾': 'beisebol',
  '🎾': 'tenis bola',
  '🏐': 'volei bola',
  '🏉': 'rugby',
  '🥇': 'ouro primeiro medalha campeao',
  '🥈': 'prata segundo medalha',
  '🥉': 'bronze terceiro medalha',
  '🏆': 'trofeu campeao vitoria',
  '🏅': 'medalha premio',
  '🎖️': 'medalha militar honra',
  '🎪': 'circo',
  '🎭': 'teatro mascaras drama',
  '🎨': 'arte pintura paleta',
  '🎬': 'cinema claquete filme',
  '🎤': 'microfone cantar karaoke',
  '🎧': 'fone de ouvido headset musica',
  '🎼': 'partitura musica',
  '🎵': 'nota musical musica',
  '🎶': 'notas musicais musica',
  '🥁': 'bateria tambor',
  '🎸': 'guitarra violao',
  '🎹': 'piano teclado',

  // --- Objetos --------------------------------------------------------------
  '💻': 'notebook laptop computador pc',
  '🖥️': 'computador monitor desktop pc',
  '⌨️': 'teclado',
  '🖱️': 'mouse',
  '🖨️': 'impressora',
  '📱': 'celular telefone smartphone',
  '☎️': 'telefone fixo',
  '📞': 'telefone chamada ligacao',
  '📟': 'pager bip',
  '📠': 'fax',
  '🔋': 'bateria carga',
  '🔌': 'tomada plugue energia',
  '💡': 'lampada ideia luz',
  '🔦': 'lanterna',
  '🕯️': 'vela',
  '🧯': 'extintor fogo',
  '🛢️': 'barril petroleo oleo',
  '💸': 'dinheiro voando gastando grana',
  '💵': 'dolar dinheiro nota',
  '💴': 'iene dinheiro',
  '💶': 'euro dinheiro',
  '💷': 'libra dinheiro',
  '🪙': 'moeda',
  '💰': 'saco de dinheiro grana',
  '💳': 'cartao de credito',
  '🧾': 'recibo nota fiscal',
  '✉️': 'envelope carta email',
  '📧': 'email',
  '📨': 'email recebido',
  '📩': 'email enviado',
  '📤': 'caixa de saida enviar',
  '📥': 'caixa de entrada receber',
  '📦': 'caixa pacote encomenda',
  '📪': 'caixa de correio fechada',
  '📫': 'caixa de correio',
  '📬': 'caixa de correio com carta',
  '🔍': 'lupa busca procurar pesquisar',
  '🔎': 'lupa busca procurar zoom',
  '🔒': 'cadeado fechado trancado seguro',
  '🔓': 'cadeado aberto destrancado',
  '🔏': 'cadeado caneta privacidade',
  '🔐': 'cadeado chave seguranca',
  '🔑': 'chave',
  '🗝️': 'chave antiga',
  '🔨': 'martelo',
  '🪓': 'machado',
  '⛏️': 'picareta minerar',
  '🛠️': 'ferramentas conserto',
  '🗡️': 'espada adaga',
  '⚔️': 'espadas batalha luta',
  '🔫': 'arma pistola',
  '🏹': 'arco e flecha',
  '🛡️': 'escudo protecao defesa',
  '🔧': 'chave inglesa ferramenta conserto',

  // --- Simbolos -------------------------------------------------------------
  '✅': 'certo ok feito check verde',
  '❌': 'errado xis nao cancelar',
  '❎': 'xis errado',
  '✔️': 'certo check marcado',
  '☑️': 'caixa marcada check',
  '⚠️': 'aviso atencao cuidado perigo',
  '🚫': 'proibido nao pode',
  '⛔': 'proibido entrada parar',
  '📛': 'cracha nome',
  '🔰': 'iniciante novato',
  '♻️': 'reciclagem reciclar',
  '✳️': 'asterisco',
  '❇️': 'brilho faisca',
  '✴️': 'estrela oito pontas',
  '🆚': 'versus contra vs',
  '🆗': 'ok',
  '🆙': 'up subir',
  '🆒': 'cool legal',
  '🆕': 'novo new',
  '🆓': 'gratis free',
  '0️⃣': 'zero numero 0',
  '1️⃣': 'um numero 1',
  '2️⃣': 'dois numero 2',
  '3️⃣': 'tres numero 3',
  '4️⃣': 'quatro numero 4',
  '5️⃣': 'cinco numero 5',
  '6️⃣': 'seis numero 6',
  '7️⃣': 'sete numero 7',
  '8️⃣': 'oito numero 8',
  '9️⃣': 'nove numero 9',
  '🔟': 'dez numero 10',
  '🔢': 'numeros digitos',
  '⏰': 'despertador alarme hora relogio',
  '⌛': 'ampulheta tempo acabou',
  '⏳': 'ampulheta tempo esperando',
  '🔥': 'fogo quente top incrivel',
  '⭐': 'estrela favorito',
  '🌟': 'estrela brilhante',
  '✨': 'brilho faiscas magia',
  '⚡': 'raio energia rapido',
  '☄️': 'cometa meteoro',
  '💧': 'gota agua',
  '🌊': 'onda mar agua',
  '❄️': 'floco de neve frio',
  '🌈': 'arco iris',
  '☀️': 'sol ensolarado',
  '🌙': 'lua noite',
  '⛅': 'sol entre nuvens parcialmente nublado',
  '☁️': 'nuvem nublado',
  '🌧️': 'chuva chovendo',
  '⛈️': 'tempestade raio chuva',
  '🌪️': 'tornado furacao',
  '🌫️': 'neblina nevoa',
  '🌀': 'ciclone espiral tontura',
};

/**
 * Tira acento e caixa para comparar.
 *
 * Quem digita rapido escreve "coracao", nao "coração". Normalizar os dois
 * lados faz as duas formas acharem a mesma coisa, e custa nada.
 */
export function normalizar(texto: string): string {
  return texto
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '');
}

/** Se o emoji responde ao que foi digitado. */
export function emojiCombina(emoji: string, buscaNormalizada: string): boolean {
  const palavras = PALAVRAS_DE_EMOJI[emoji];
  if (!palavras) return false;
  return normalizar(palavras).includes(buscaNormalizada);
}
